package cc.joycreator.joybrush.core.doc

import cc.joycreator.joybrush.core.paint.Tiles
import kotlinx.serialization.Serializable

const val DOC_FORMAT = "joybrush.document"
const val DOC_VERSION = 1

/**
 * The engine's tile size, NOT a second copy of it. `Cel.tiles` holds keys the engine wrote with
 * `paint.Tiles`, so a second literal here would let the two drift apart and send every tile in every
 * saved document to the wrong place without anything complaining. Lead ruling, 2026-09-28.
 */
const val TILE_SIZE = Tiles.SIZE

/**
 * The in-memory shape of a Joy Brush drawing, and the whole of `document.json`.
 *
 * This is a CONTRACT (JB-0.02). Save/open (JB-0.08), the animation board (JB-3.01) and every exporter
 * read it. The rules it obeys:
 *
 *  - A document is an UNBOUNDED canvas at one pixel density. "Unbounded" is why [RectPx] and the tile
 *    keys are signed and why a board may sit at a negative x or y.
 *  - Paper is a SETTING, not a layer. It is under the art and is optionally flattened into an export.
 *  - A board is a named rectangle that defines export bounds. A new document has one CANVAS board.
 *  - A layer is PAINT (pixels are the truth) or INK (stroke records are the truth). Nothing else.
 *  - Animation does NOT get a second layer system: a layer is static, or animated in ONE ANIMATION
 *    board. Several frames may point at ONE cel, which is exactly what "hold" and "duplicate as link"
 *    are. A static layer is a held background, visible behind or in front of every frame.
 *  - Every id is a String. UUIDs are generated by the CALLER (this module has no platform uuid), which
 *    is also why tests can pass fixed ids.
 *
 * NO PIXELS live here. Tiles are referenced by key and stroke files by path; the bytes are somebody
 * else's problem (JB-0.08).
 */
@Serializable data class RectPx(val x: Int, val y: Int, val w: Int, val h: Int)

@Serializable data class Paper(
    val color: String = "#FFFFFF",          // #RRGGBB
    val textureId: String? = null,          // a grain asset id, null = plain
    val textureScale: Float = 1f,
    val includeInExport: Boolean = false,   // the "Include paper" checkbox default
)

@Serializable enum class BoardKind { CANVAS, ANIMATION, SPRITE, PUPPET, CHARACTER }

@Serializable data class Frame(
    val id: String,
    val holdFrames: Int = 1,                // shown for this many ticks of the board's fps
)

@Serializable data class SpriteGrid(val cols: Int, val rows: Int, val cellW: Int, val cellH: Int)

@Serializable data class Board(
    val id: String,
    val name: String,
    val kind: BoardKind,
    val rect: RectPx,
    val clipToBoard: Boolean = false,
    val fps: Float = 12f,                   // ANIMATION only
    val frames: List<Frame> = emptyList(),  // ANIMATION only, in play order
    val grid: SpriteGrid? = null,           // SPRITE only
)

@Serializable enum class LayerKind { PAINT, INK }
@Serializable enum class BlendMode { NORMAL, MULTIPLY, SCREEN, OVERLAY, ADD, DARKEN, LIGHTEN, ERASE_BELOW }

@Serializable data class Cel(
    val id: String,
    val tiles: List<String> = emptyList(),  // PAINT: tile keys "tx_ty" that exist (sparse)
    val strokesFile: String? = null,        // INK: path inside the document zip
)

@Serializable data class Layer(
    val id: String,
    val name: String,
    val kind: LayerKind,
    val visible: Boolean = true,
    val locked: Boolean = false,
    val opacity: Float = 1f,
    val blend: BlendMode = BlendMode.NORMAL,
    val animatedIn: String? = null,         // board id, or null = static
    val cels: List<Cel>,                    // static: exactly 1; animated: >= 1
    val frameCel: Map<String, String> = emptyMap(), // animated: frame id -> cel id
)

@Serializable data class JbDocument(
    val format: String = DOC_FORMAT,
    val version: Int = DOC_VERSION,
    val id: String,
    val name: String,
    val paper: Paper = Paper(),
    val boards: List<Board>,
    val layers: List<Layer>,                // bottom -> top
    val activeLayerId: String? = null,
    val activeBoardId: String? = null,
)
