package cc.joycreator.joybrush.core.doc

import cc.joycreator.joybrush.core.paint.Tiles
import kotlinx.serialization.Serializable

const val DOC_FORMAT = "joybrush.document"
/**
 * 4: the paper carries a look, a tint and two sliders (JB-9.05, R10).
 * 3: a layer may carry a [Layer.mask] and be [Layer.clip]ped (JB-2.23, Lead ruling R48).
 */
const val DOC_VERSION = 4

/**
 * The engine's tile size, NOT a second copy of it. `Cel.tiles` holds keys the engine wrote with
 * `paint.Tiles`, so a second literal here would let the two drift apart and send every tile in every
 * saved document to the wrong place without anything complaining. Lead ruling, 2026-09-28.
 */
const val TILE_SIZE = Tiles.SIZE

/**
 * The in-memory shape of a Joy Brush drawing, and the whole of `document.json`.
 *
 * This is a CONTRACT (JB-0.02). Save/open (JB-0.08), the animation board (JB-3.01) and every exporter
 * read it. The rules it obeys:
 *
 *  - A document is an UNBOUNDED canvas at one pixel density. "Unbounded" is why [RectPx] and the tile
 *    keys are signed and why a board may sit at a negative x or y.
 *  - Paper is a SETTING, not a layer. It is under the art and is optionally flattened into an export.
 *  - A board is a named rectangle that defines export bounds. A new document has one CANVAS board.
 *  - A layer is PAINT (pixels are the truth) or INK (stroke records are the truth). Nothing else.
 *  - Animation does NOT get a second layer system: a layer is static, or animated in ONE ANIMATION
 *    board. Several frames may point at ONE cel, which is exactly what "hold" and "duplicate as link"
 *    are. A static layer is a held background, visible behind or in front of every frame.
 *  - Every id is a String. UUIDs are generated by the CALLER (this module has no platform uuid), which
 *    is also why tests can pass fixed ids.
 *
 * NO PIXELS live here. Tiles are referenced by key and stroke files by path; the bytes are somebody
 * else's problem (JB-0.08).
 */
@Serializable data class RectPx(val x: Int, val y: Int, val w: Int, val h: Int)

/**
 * The paper the drawing sits on: a SETTING of the document, saved with it, and under the art.
 *
 * **A paper is a LOOK plus a SURFACE (JB-9.05, R10 §3).** The **look** is what you see — a colour
 * picture, re-tintable — named by `lookId` out of the paper catalogue. The **surface** is what the
 * brushes feel, named by `textureId`, and is the *same* catalogue's other list. They are separate
 * because they answer different questions and are chosen separately: a rice paper's fibres are in its
 * look, and its tooth is its surface.
 *
 * **`textureId` and `textureScale` keep their v3 NAMES, deliberately.** They are read and written
 * exactly as v3 wrote them, so a v3 file's `textureId` means the same thing it meant then and nothing
 * has to be migrated. `textureScale` is the sheet's **Scale** slider and multiplies the look and the
 * surface together, so one slider sizes the whole paper.
 *
 * **`light` is a three-state field and `null` is not `false`.** Null means "whatever the look says",
 * which is how AMOLED black ships: its `lightByDefault` is false, because lighting a relief on a true
 * black greys it into a colour that is not black. An explicit true or false is the owner overriding
 * the catalogue for this drawing. [cc.joycreator.joybrush.core.paper.PaperState] is what reads it.
 */
@Serializable data class Paper(
    val color: String = "#FFFFFF",          // #RRGGBB. The flat colour when lookId == null; ignored for the base when a look is set
    val textureId: String? = null,          // the SURFACE id (catalogue), null = smooth. Name kept for compatibility
    val textureScale: Float = 1f,           // the sheet's Scale: multiplies the surface AND look physical size, 0.25..4
    val includeInExport: Boolean = false,   // the "Include paper" checkbox default
    val lookId: String? = null,             // v4. Catalogue look id, null = flat `color`
    val tint: String? = null,               // v4. "#RRGGBB" recolours the look; null = the look's own colours
    val show: Float = 1f,                   // v4. 0..1 how visible the look + relief are (0 = flat base colour)
    val bite: Float = 1f,                   // v4. 0..1 how strongly brushes feel the surface
    val light: Boolean? = null,             // v4. relief lighting; null = the look's lightByDefault
)

/**
 * What a board is FOR. The constant NAME is the whole of what lands in `document.json`
 * (`"kind": "CANVAS"`) — there is no number in the file.
 *
 * SERIALISED: new constants are APPEND-ONLY and require bumping DOC_VERSION (or the brush "version"). See LEAD_RULINGS R3.
 *
 * Why the rule is a rule: reading IGNORES keys it has never heard of, but not VALUES. An older app
 * handed a kind it does not have throws, and [DocJson.decode] says so as a [DocException]. That is
 * the intended answer, not an oversight — quietly falling back to CANVAS would look like it worked
 * and then write "CANVAS" out again on the next save, which is how a drawing loses its boards for
 * good. Bumping [DOC_VERSION] alongside the new constant turns that parse error into
 * [DocOps.validate] saying "from a newer Joy Brush", which the person can act on.
 *
 * So: append at the END, and never rename or delete a name some saved file already holds.
 */
@Serializable enum class BoardKind { CANVAS, ANIMATION, SPRITE, PUPPET, CHARACTER }

@Serializable data class Frame(
    val id: String,
    val holdFrames: Int = 1,                // shown for this many ticks of the board's fps
)

@Serializable data class SpriteGrid(val cols: Int, val rows: Int, val cellW: Int, val cellH: Int)

@Serializable data class Board(
    val id: String,
    val name: String,
    val kind: BoardKind,
    val rect: RectPx,
    val clipToBoard: Boolean = false,
    val fps: Float = 12f,                   // ANIMATION only
    val frames: List<Frame> = emptyList(),  // ANIMATION only, in play order
    val grid: SpriteGrid? = null,           // SPRITE only
)

/**
 * A layer is PAINT (pixels are the truth) or INK (stroke records are the truth), and this pair is
 * the whole of it — animation does not get a third kind. The constant NAME is what lands in
 * `document.json` (`"kind": "INK"`).
 *
 * SERIALISED: new constants are APPEND-ONLY and require bumping DOC_VERSION (or the brush "version"). See LEAD_RULINGS R3.
 *
 * Two constants with a one-letter difference between them (PAINT vs PAINTER) are two kinds the app
 * would then have to keep apart forever, so the names are as much a contract as the set is: append
 * at the END, never rename, and bump [DOC_VERSION] in the same change. A kind a build does not have
 * is refused by name (a [DocException] from [DocJson.decode]), never guessed at.
 */
@Serializable enum class LayerKind { PAINT, INK }
/**
 * How a layer combines with what is under it. The constant NAME is what lands in `document.json`
 * (`"blend": "MULTIPLY"`).
 *
 * SERIALISED: new constants are APPEND-ONLY and require bumping DOC_VERSION (or the brush "version"). See LEAD_RULINGS R3.
 *
 * Every name here is a promise the renderer has to keep, so the set should grow only when the
 * renderer grows — a name nothing composites is a promise nobody kept, and by then a saved file may
 * depend on it. An unknown blend is refused rather than approximated, because a blend that quietly
 * becomes NORMAL and is then re-saved has changed the painting without telling anybody. Append at
 * the END, never rename, and bump [DOC_VERSION] with it.
 */
/**
 * The blend modes a layer composites with. The first eight are Joy Brush's own; the nineteen below
 * the fold are the Studio's, appended in the Studio's `BlendModes.ALL` order (JB-2.20a, R23).
 *
 * **THE ORDER IS THE STUDIO'S, BUT THE ORDINALS DO NOT *EQUAL* THE STUDIO'S `modeCode`, and an
 * earlier version of this comment claimed they did.** That claim was false and was filed against it
 * as a MAJOR false-claim finding: `ERASE_BELOW` is Joy Brush's own insertion at ordinal 7, so every
 * Studio mode after it is shifted by one, and `DARKEN`/`LIGHTEN` are the Studio's own non-adjacent
 * codes, so the divergence is larger than that. Nothing reads `BlendMode.ordinal` in production and
 * nothing is miscomposited today — but the claim mattered because it said the parity proof *rides
 * on* the ordinal, which is backwards: `BlendParityTest` walks by Studio **code** and looks the
 * mode up by name, so it would keep working even if this list were reordered. What the order
 * actually buys is that a human reading the two lists side by side finds the same sequence.
 *
 * `ERASE_BELOW` is the one constant with no Studio counterpart — it is Joy Brush's own — which is
 * why the enum has 27 entries where the Studio has 26.
 *
 * APPEND-ONLY: these names are on-disk tokens, so a rename or a delete breaks saved files. R3.
 */
@Serializable enum class BlendMode {
    NORMAL, MULTIPLY, SCREEN, OVERLAY, ADD, DARKEN, LIGHTEN, ERASE_BELOW,
    // ---- appended, in `BlendModes.ALL` / modeCode order. FROZEN (R3, DOC_VERSION 2) ----
    DIFFERENCE, COLOR, COLOR_DODGE, COLOR_BURN, LINEAR_BURN,
    HARD_LIGHT, SOFT_LIGHT, VIVID_LIGHT, LINEAR_LIGHT, PIN_LIGHT, HARD_MIX,
    EXCLUSION, SUBTRACT, DIVIDE, DARKER_COLOR, LIGHTER_COLOR,
    HUE, SATURATION, LUMINOSITY,
}

@Serializable data class Cel(
    val id: String,
    val tiles: List<String> = emptyList(),  // PAINT: tile keys "tx_ty" that exist (sparse)
    val strokesFile: String? = null,        // INK: path inside the document zip
)

@Serializable data class Layer(
    val id: String,
    val name: String,
    val kind: LayerKind,
    val visible: Boolean = true,
    val locked: Boolean = false,
    val opacity: Float = 1f,
    val blend: BlendMode = BlendMode.NORMAL,
    val animatedIn: String? = null,         // board id, or null = static
    val cels: List<Cel>,                    // static: exactly 1; animated: >= 1
    val frameCel: Map<String, String> = emptyMap(), // animated: frame id -> cel id
    /**
     * The layer's mask (JB-2.23, R48), or null for none. Its OWN field, not one of [cels]: every rule that counts cels
     * (static = 1, animation frames, the exporters) stays exactly as it was. Coverage is the tiles' R channel; alpha is
     * ignored; a tile the mask does not have is full coverage (255), so a new mask shows everything. PAINT layers only.
     */
    val mask: Cel? = null,
    /** Clipped (Photoshop's clipping mask): shown only where the nearest unclipped layer below has paint. */
    val clip: Boolean = false,
)

@Serializable data class JbDocument(
    val format: String = DOC_FORMAT,
    val version: Int = DOC_VERSION,
    val id: String,
    val name: String,
    val paper: Paper = Paper(),
    val boards: List<Board>,
    val layers: List<Layer>,                // bottom -> top
    val activeLayerId: String? = null,
    val activeBoardId: String? = null,
)
