package cc.joycreator.joybrush.core.media

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * CPU reference tests for JB-2.40 §Q1 plain-on-media bake.
 *
 * All expected bytes/channel values are hand-worked, not generated by the implementation.
 * Float assertions compare raw bits (toRawBits) so signed zero and NaN payloads are checked,
 * since == would hide -0.0 vs +0.0 and NaN != NaN.
 */
class MediaPlainBakeTest {

    private fun assertFloatBits(expected: FloatArray, actual: FloatArray, what: String) {
        assertEquals(expected.size, actual.size, "$what size")
        for (i in expected.indices) {
            assertEquals(
                expected[i].toRawBits(),
                actual[i].toRawBits(),
                "$what[$i]: expected bits ${expected[i].toRawBits()} (${expected[i]}) vs ${actual[i].toRawBits()} (${actual[i]})",
            )
        }
    }

    private fun assertGround(expected: ByteArray, actual: ByteArray, what: String = "ground") {
        assertEquals(expected.size, actual.size, "$what size")
        assertTrue(expected.contentEquals(actual), "$what bytes: expected ${expected.map { it.toInt() and 0xFF }} vs ${actual.map { it.toInt() and 0xFF }}")
    }

    @Test fun mixedPixelsBakeCopiesLookAndClearsStateExceptCrush() {
        // 3 pixels: pixel 0 untouched (coverage 0), pixels 1-2 baked (coverage 1 and 0.5).
        val ground = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120)
        val look = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
        val coverage = floatArrayOf(0f, 1f, 0.5f)
        val stores = mapOf(
            "p0" to floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f, 9f, 10f, 11f, 12f),
            "p1" to floatArrayOf(13f, 14f, 15f, 16f, 17f, 18f, 19f, 20f, 21f, 22f, 23f, 24f),
            "paper" to floatArrayOf(101f, 102f, 103f, 104f, 105f, 106f, 107f, 108f, 109f, 110f, 111f, 112f),
            "w0" to floatArrayOf(201f, 202f, 203f, 204f, 205f, 206f, 207f, 208f, 209f, 210f, 211f, 212f),
            "w1" to floatArrayOf(301f, 302f, 303f, 304f, 305f, 306f, 307f, 308f, 309f, 310f, 311f, 312f),
        )

        val out = MediaPlainBake.bake(ground, look, coverage, stores)

        // Hand-worked: pixel 0 keeps ground, pixels 1-2 take look exactly.
        assertGround(byteArrayOf(10, 20, 30, 40, 5, 6, 7, 8, 9, 10, 11, 12), out.ground)
        assertFloatBits(floatArrayOf(1f, 2f, 3f, 4f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f), out.stores.getValue("p0"), "p0")
        assertFloatBits(floatArrayOf(13f, 14f, 15f, 16f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f), out.stores.getValue("p1"), "p1")
        assertFloatBits(
            floatArrayOf(101f, 102f, 103f, 104f, 105f, 0f, 0f, 0f, 109f, 0f, 0f, 0f),
            out.stores.getValue("paper"),
            "paper",
        )
        assertFloatBits(floatArrayOf(201f, 202f, 203f, 204f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f), out.stores.getValue("w0"), "w0")
        assertFloatBits(floatArrayOf(301f, 302f, 303f, 304f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f), out.stores.getValue("w1"), "w1")
    }

    @Test fun thresholdIsStrictlyGreaterThanOneOver255() {
        val thr = 1f / 255f
        assertEquals((1f / 255f).toRawBits(), MediaPlainBake.COVERAGE_THRESHOLD.toRawBits(), "threshold is exactly 1f/255f")
        val justAbove = Float.fromBits(thr.toRawBits() + 1)
        val justBelow = Float.fromBits(thr.toRawBits() - 1)
        assertTrue(justAbove > thr, "adjacent float above must exceed threshold")
        assertTrue(justBelow < thr, "adjacent float below must be under threshold")
        assertTrue(justAbove >= 0f && justAbove <= 1f, "adjacent above stays in 0..1")
        assertTrue(justBelow >= 0f && justBelow <= 1f, "adjacent below stays in 0..1")

        // Pixels: exact threshold preserves, just-below preserves, just-above bakes.
        val ground = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120)
        val look = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
        val coverage = floatArrayOf(thr, justBelow, justAbove)
        val stores = mapOf(
            "p0" to floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f, 9f, 10f, 11f, 12f),
            "paper" to floatArrayOf(21f, 22f, 23f, 24f, 25f, 26f, 27f, 28f, 29f, 30f, 31f, 32f),
        )

        val out = MediaPlainBake.bake(ground, look, coverage, stores)

        assertGround(byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80, 9, 10, 11, 12), out.ground)
        assertFloatBits(floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f, 0f, 0f, 0f, 0f), out.stores.getValue("p0"), "p0 threshold")
        assertFloatBits(
            floatArrayOf(21f, 22f, 23f, 24f, 25f, 26f, 27f, 28f, 29f, 0f, 0f, 0f),
            out.stores.getValue("paper"),
            "paper threshold",
        )
    }

    @Test fun crushRetainedAsRawBitsWhileFlakesCleared() {
        // Pixel 0 baked, pixel 1 untouched. Crush (paper r) keeps raw bits even when NaN; g/b/a clear to +0.
        val nanPayload = Float.fromBits(0x7FC00001)
        val nanOther = Float.fromBits(0x7FC00002)
        val ground = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80)
        val look = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8)
        val coverage = floatArrayOf(1f, 0f)
        val paperIn = floatArrayOf(nanPayload, 5f, 6f, 7f, -0.0f, nanOther, -0.0f, 1f)
        val p0In = floatArrayOf(1f, 2f, 3f, 4f, -0.0f, Float.fromBits(0x7FC00003), 5f, -0.0f)

        val out = MediaPlainBake.bake(ground, look, coverage, mapOf("paper" to paperIn, "p0" to p0In))

        assertGround(byteArrayOf(1, 2, 3, 4, 50, 60, 70, 80), out.ground)
        val paperOut = out.stores.getValue("paper")
        // Baked pixel: r keeps NaN payload bits, g/b/a are +0 (bits 0).
        assertEquals(0x7FC00001, paperOut[0].toRawBits(), "baked crush keeps NaN payload")
        assertEquals(0, paperOut[1].toRawBits(), "baked paper g is +0")
        assertEquals(0, paperOut[2].toRawBits(), "baked paper b is +0")
        assertEquals(0, paperOut[3].toRawBits(), "baked paper a is +0")
        // Untouched pixel: all raw bits preserved, including -0.0 and NaN payload.
        assertEquals((-0.0f).toRawBits(), paperOut[4].toRawBits(), "untouched crush keeps -0.0")
        assertEquals(0x7FC00002, paperOut[5].toRawBits(), "untouched paper g keeps NaN payload")
        assertEquals((-0.0f).toRawBits(), paperOut[6].toRawBits(), "untouched paper b keeps -0.0")
        assertEquals(1f.toRawBits(), paperOut[7].toRawBits(), "untouched paper a kept")

        val p0Out = out.stores.getValue("p0")
        assertEquals(0, p0Out[0].toRawBits(), "baked p0 r cleared to +0")
        assertEquals(0, p0Out[1].toRawBits(), "baked p0 g cleared")
        assertEquals(0, p0Out[2].toRawBits(), "baked p0 b cleared")
        assertEquals(0, p0Out[3].toRawBits(), "baked p0 a cleared")
        assertEquals((-0.0f).toRawBits(), p0Out[4].toRawBits(), "untouched p0 keeps -0.0")
        assertEquals(0x7FC00003, p0Out[5].toRawBits(), "untouched p0 keeps NaN payload")
        assertEquals(5f.toRawBits(), p0Out[6].toRawBits(), "untouched p0 kept")
        assertEquals((-0.0f).toRawBits(), p0Out[7].toRawBits(), "untouched p0 keeps -0.0")
    }

    @Test fun untouchedPixelsPreserveRawBitsIncludingSignedZeroAndInfinities() {
        // Coverage -0.0 is valid (equals 0) and must not bake; infinities in STATE are preserved when untouched.
        val ground = byteArrayOf(10, 20, 30, 40)
        val look = byteArrayOf(1, 2, 3, 4)
        val coverage = floatArrayOf(-0.0f)
        val stateIn = floatArrayOf(-0.0f, Float.fromBits(0x7FC0000A), Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY)

        val out = MediaPlainBake.bake(ground, look, coverage, mapOf("p1" to stateIn))

        assertGround(byteArrayOf(10, 20, 30, 40), out.ground, "unbaked ground keeps bytes")
        val p1Out = out.stores.getValue("p1")
        assertEquals((-0.0f).toRawBits(), p1Out[0].toRawBits(), "keeps -0.0, not +0")
        assertEquals(0x7FC0000A, p1Out[1].toRawBits(), "keeps NaN payload")
        assertEquals(Float.POSITIVE_INFINITY.toRawBits(), p1Out[2].toRawBits(), "keeps +Inf without sanitizing")
        assertEquals(Float.NEGATIVE_INFINITY.toRawBits(), p1Out[3].toRawBits(), "keeps -Inf without sanitizing")
    }

    @Test fun missingStoresStayMissingAndEmptyStaysEmpty() {
        val ground = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80)
        val look = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8)
        val coverage = floatArrayOf(1f, 0f)
        val paperIn = floatArrayOf(11f, 12f, 13f, 14f, 15f, 16f, 17f, 18f)

        val out = MediaPlainBake.bake(ground, look, coverage, mapOf("paper" to paperIn))
        assertEquals(setOf("paper"), out.stores.keys, "no stores invented")
        assertFloatBits(floatArrayOf(11f, 0f, 0f, 0f, 15f, 16f, 17f, 18f), out.stores.getValue("paper"), "paper")
        assertGround(byteArrayOf(1, 2, 3, 4, 50, 60, 70, 80), out.ground)

        val emptyOut = MediaPlainBake.bake(ground, look, coverage, emptyMap())
        assertTrue(emptyOut.stores.isEmpty(), "empty stays empty")
        assertGround(byteArrayOf(1, 2, 3, 4, 50, 60, 70, 80), emptyOut.ground, "ground still bakes with no stores")
    }

    @Test fun inputsUnchangedAndOutputsAreFreshCopies() {
        val ground = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80)
        val look = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8)
        val coverage = floatArrayOf(1f, 0f)
        val p0In = floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f)
        val paperIn = floatArrayOf(9f, 10f, 11f, 12f, 13f, 14f, 15f, 16f)
        val stores = mapOf("p0" to p0In, "paper" to paperIn)
        val groundSnap = ground.copyOf()
        val lookSnap = look.copyOf()
        val coverageSnap = coverage.copyOf()
        val p0Snap = p0In.copyOf()
        val paperSnap = paperIn.copyOf()

        val out = MediaPlainBake.bake(ground, look, coverage, stores)

        // Inputs unchanged.
        assertTrue(groundSnap.contentEquals(ground), "ground input unchanged")
        assertTrue(lookSnap.contentEquals(look), "look input unchanged")
        assertTrue(coverageSnap.contentEquals(coverage), "coverage input unchanged")
        assertFloatBits(p0Snap, p0In, "p0 input unchanged")
        assertFloatBits(paperSnap, paperIn, "paper input unchanged")

        // Outputs alias no input.
        assertTrue(out.ground !== ground, "ground output is a copy")
        assertTrue(out.ground !== look, "ground output aliases neither input")
        assertTrue(out.stores !== stores, "stores map is a copy")
        assertTrue(out.stores.getValue("p0") !== p0In, "p0 output is a copy")
        assertTrue(out.stores.getValue("paper") !== paperIn, "paper output is a copy")

        // Mutating the output does not touch the input; mutating input after bake does not touch output.
        out.ground[0] = 99.toByte()
        out.stores.getValue("p0")[0] = 99f
        assertTrue(groundSnap.contentEquals(ground), "input ground still unchanged after output mutation")
        assertEquals(1f.toRawBits(), p0In[0].toRawBits(), "input p0 still unchanged after output mutation")
        ground[0] = 77.toByte()
        assertEquals(99.toByte(), out.ground[0], "output ground stable after input mutation")
        ground[0] = groundSnap[0]
    }

    @Test fun invalidShapesRejected() {
        val okGround = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80)
        val okLook = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8)
        val okCoverage = floatArrayOf(0f, 0f)

        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(byteArrayOf(1, 2, 3, 4, 5), byteArrayOf(1, 2, 3, 4, 5), floatArrayOf(0f))
        }
        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(okGround, byteArrayOf(1, 2, 3, 4), okCoverage, emptyMap())
        }
        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(okGround, okLook, floatArrayOf(0f), emptyMap())
        }
        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(okGround, okLook, floatArrayOf(0f, 0f, 0f), emptyMap())
        }
        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(okGround, okLook, okCoverage, mapOf("p0" to floatArrayOf(1f, 2f, 3f, 4f)))
        }
        assertFailsWith<IllegalArgumentException> {
            MediaPlainBake.bake(okGround, okLook, okCoverage, mapOf("p0" to FloatArray(12) { it.toFloat() }))
        }
    }

    @Test fun invalidCoverageRejectedAndEdgesAccepted() {
        val ground = byteArrayOf(10, 20, 30, 40)
        val look = byteArrayOf(1, 2, 3, 4)
        for (bad in listOf(Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, -1f, -0.001f, 1.000001f, 2f)) {
            assertFailsWith<IllegalArgumentException>("coverage $bad must fail") {
                MediaPlainBake.bake(ground, look, floatArrayOf(bad), emptyMap())
            }
        }
        // Edges that must be accepted: -0.0 (equals 0), 0, threshold, 1.
        for (good in listOf(-0.0f, 0f, 1f / 255f, 1f)) {
            MediaPlainBake.bake(ground, look, floatArrayOf(good), emptyMap())
        }
    }

    @Test fun unknownStoreIdsRejected() {
        val ground = byteArrayOf(10, 20, 30, 40)
        val look = byteArrayOf(1, 2, 3, 4)
        val coverage = floatArrayOf(0f)
        for (bad in listOf("g", "px", "P0", "paper ", "", "layer#p0", "w2")) {
            assertFailsWith<IllegalArgumentException>("store $bad must fail") {
                MediaPlainBake.bake(ground, look, coverage, mapOf(bad to floatArrayOf(1f, 2f, 3f, 4f)))
            }
        }
        // All real short names are accepted.
        MediaPlainBake.bake(
            ground,
            look,
            coverage,
            mapOf(
                "p0" to floatArrayOf(1f, 2f, 3f, 4f),
                "p1" to floatArrayOf(1f, 2f, 3f, 4f),
                "paper" to floatArrayOf(1f, 2f, 3f, 4f),
                "w0" to floatArrayOf(1f, 2f, 3f, 4f),
                "w1" to floatArrayOf(1f, 2f, 3f, 4f),
            ),
        )
    }
}
