// JB-2.20b — the VALUE PIN, on a real GL driver: does the composite shader give the answers the Studio's Java gives?
// Run: cd joybrush/tools && CHROME=<chrome/edge exe> node blend_gpu_check.js     (needs playwright-core, like shader_check.js)
//
// What it compares. `BlendGolden.kt` is an OBSERVATION of the Studio's own Java (`BlendModes.blend`), generated by
// tools/gen_blend_golden.sh: 1189 (backdrop, source) pairs x 26 modes. This script draws `jb_composite.frag` (which
// includes the GENERATED jb_blend.glsl) for the in-range pairs at seven (source alpha, backdrop alpha) combinations,
// into float targets so the 8-bit rounding is not part of the question, and compares every pixel with the W3C formula
// applied to the golden blend term:
//     co = sa(1-da)Cs + sa*da*clamp(B) + (1-sa)da*Cb      a = sa + da(1-sa)         (ERASE_BELOW: d*(1-sa))
// It is the same formula core/render/Blend.kt uses, so a pass means: GPU shader == CPU renderer == the Studio's Java.
// Pass = "mismatches":0 and "checked" > 100000.
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright-core');
const dir = path.join(__dirname, '..', 'shaders');
function src(name) {
  return fs.readFileSync(path.join(dir, name), 'utf8').split('\n').map(l => {
    const m = l.trim().match(/^#include\s+"([^"]+)"/);
    return m ? src(m[1]) : l;
  }).join('\n');
}
const golden = fs.readFileSync(path.join(__dirname, '..', 'core', 'src', 'commonTest', 'kotlin', 'cc', 'joycreator',
  'joybrush', 'core', 'blend', 'BlendGolden.kt'), 'utf8');
function block(text, startIdx) {           // the numbers inside the floatArrayOf( ... ) that opens at/after startIdx
  const open = text.indexOf('floatArrayOf(', startIdx) + 'floatArrayOf('.length;
  const close = text.indexOf(')', open);
  return { nums: text.slice(open, close).split(',').map(s => s.trim()).filter(Boolean).map(s => parseFloat(s.replace(/f$/, ''))), end: close };
}
const BS = block(golden, golden.indexOf('val BS')).nums;
let EXP = [];
let at = golden.indexOf('private fun part0');
for (let i = 0; i < 12; i++) { const b = block(golden, golden.indexOf('private fun part' + i)); EXP = EXP.concat(b.nums); }
const MODES = 26, PAIRS_ALL = 1189, PAIRS = 1129;   // the last 60 are out of range: straight colours above 1 are not pixels
if (BS.length !== PAIRS_ALL * 6 || EXP.length !== PAIRS_ALL * MODES * 3) {
  console.log(JSON.stringify({ error: 'golden parse', bs: BS.length, exp: EXP.length })); process.exit(1);
}
const ALPHAS = [[1, 1], [0.5, 1], [1, 0.5], [0.5, 0.5], [0.25, 0.75], [0, 1], [1, 0]];   // [sa, da]
const A = ALPHAS.length;
const clamp01 = v => Math.min(1, Math.max(0, v));

const VS = `#version 300 es
layout(location = 0) in vec2 a;
out vec2 v_uv;
void main() { v_uv = a; gl_Position = vec4(a * 2.0 - 1.0, 0.0, 1.0); }`;

(async () => {
  const exe = process.env.CHROME ? null : fs.readdirSync('/opt/pw-browsers').find(d => d.startsWith('chromium-'));
  const browser = await chromium.launch({
    executablePath: process.env.CHROME || `/opt/pw-browsers/${exe}/chrome-linux/chrome`,
    args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
  });
  const page = await browser.newPage();
  const out = await page.evaluate(({ vs, fsrc, BS, EXP, ALPHAS, PAIRS, MODES }) => {
    const c = document.createElement('canvas');
    const gl = c.getContext('webgl2');
    if (!gl) return { error: 'no webgl2' };
    if (!gl.getExtension('EXT_color_buffer_float')) return { error: 'no EXT_color_buffer_float' };
    const mk = (t, s) => { const sh = gl.createShader(t); gl.shaderSource(sh, s); gl.compileShader(sh);
      if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(sh)); return sh; };
    const p = gl.createProgram(); gl.attachShader(p, mk(gl.VERTEX_SHADER, vs)); gl.attachShader(p, mk(gl.FRAGMENT_SHADER, fsrc));
    gl.linkProgram(p); if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p));
    const A = ALPHAS.length, W = PAIRS, H = (MODES + 1) * A;      // the extra block of rows is ERASE_BELOW
    const layerData = new Float32Array(W * H * 4), backData = new Float32Array(W * H * 4);
    for (let m = 0; m <= MODES; m++) for (let a = 0; a < A; a++) for (let i = 0; i < W; i++) {
      const [sa, da] = ALPHAS[a]; const o = ((m * A + a) * W + i) * 4;
      for (let ch = 0; ch < 3; ch++) { backData[o + ch] = BS[i * 6 + ch] * da; layerData[o + ch] = BS[i * 6 + 3 + ch] * sa; }
      backData[o + 3] = da; layerData[o + 3] = sa;
    }
    function ftex(data, unit) {
      const t = gl.createTexture(); gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, W, H, 0, gl.RGBA, gl.FLOAT, data);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); return t;
    }
    ftex(layerData, 0); ftex(backData, 1);
    const target = gl.createTexture(); gl.activeTexture(gl.TEXTURE2); gl.bindTexture(gl.TEXTURE_2D, target);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, W, H, 0, gl.RGBA, gl.FLOAT, null);
    const fbo = gl.createFramebuffer(); gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, target, 0);
    if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.FRAMEBUFFER_COMPLETE) return { error: 'float target incomplete' };
    gl.viewport(0, 0, W, H); gl.disable(gl.BLEND); gl.enable(gl.SCISSOR_TEST);
    const quad = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, quad);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([0,0, 1,0, 0,1, 1,1]), gl.STATIC_DRAW);
    const vao = gl.createVertexArray(); gl.bindVertexArray(vao); gl.enableVertexAttribArray(0); gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 0, 0);
    gl.useProgram(p); const u = n => gl.getUniformLocation(p, n);
    gl.uniform1f(u('u_layerOpacity'), 1); gl.uniform1i(u('u_layer'), 0); gl.uniform1i(u('u_backdrop'), 1);
    for (let m = 0; m <= MODES; m++) {
      gl.scissor(0, m * A, W, A);
      gl.uniform1f(u('u_mode'), m === MODES ? -1 : m);
      gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
    }
    const px = new Float32Array(W * H * 4); gl.readPixels(0, 0, W, H, gl.RGBA, gl.FLOAT, px);
    const clamp01 = v => Math.min(1, Math.max(0, v));
    let checked = 0, mismatches = 0, worst = 0; const first = [];
    for (let m = 0; m <= MODES; m++) for (let a = 0; a < A; a++) for (let i = 0; i < W; i++) {
      const [sa, da] = ALPHAS[a]; const o = ((m * A + a) * W + i) * 4;
      const cb = [BS[i * 6], BS[i * 6 + 1], BS[i * 6 + 2]], cs = [BS[i * 6 + 3], BS[i * 6 + 4], BS[i * 6 + 5]];
      const want = [0, 0, 0, 0];
      for (let ch = 0; ch < 3; ch++) {
        if (m === MODES) want[ch] = backData[o + ch] * (1 - sa);
        else {
          const B = clamp01(EXP[i * MODES * 3 + m * 3 + ch]);
          want[ch] = sa * (1 - da) * cs[ch] + sa * da * B + (1 - sa) * da * cb[ch];
        }
      }
      want[3] = m === MODES ? da * (1 - sa) : sa + da * (1 - sa);
      // sa == 0: the shader hands the backdrop back untouched
      if (sa === 0 && m !== MODES) { for (let ch = 0; ch < 3; ch++) want[ch] = backData[o + ch]; want[3] = da; }
      for (let ch = 0; ch < 4; ch++) {
        checked++;
        const err = Math.abs(px[o + ch] - want[ch]); if (err > worst) worst = err;
        if (!(err <= 2e-4)) { mismatches++; if (first.length < 8) first.push({ mode: m, alpha: ALPHAS[a], pair: i, ch, got: px[o + ch], want: want[ch] }); }
      }
    }
    return { checked, mismatches, worst, first, glError: gl.getError() };
  }, { vs: VS, fsrc: src('jb_composite.frag'), BS, EXP, ALPHAS, PAIRS, MODES }).catch(e => ({ error: String(e) }));
  console.log(JSON.stringify(out));
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
