package cc.joycreator.joybrush.core.blend

import cc.joycreator.joybrush.core.doc.BlendMode
import cc.joycreator.joybrush.core.render.Blend
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * JB-2.20a test 1 and test 3: Joy Brush's `BlendRgb` is equal to the Studio's `BlendModes.blend`
 * on every golden row, for every mode — and the eight original modes do not move.
 *
 * WHY THIS TEST IS WORTH ANYTHING. R23: core is pure Kotlin and cannot call the Studio's Java, so
 * the two copies of these 26 equations are tied together by a generated table and a drift check,
 * never by somebody reading both and deciding they agree. The table is generated by RUNNING the
 * Studio's own code (`tools/blend-golden/GenBlendGolden.java` compiles the real
 * `BlendModes.java`), so a value in it is an observation of the Studio and not a claim about it.
 * That makes this the test which would fail if the Kotlin transcription were wrong — which is the
 * failure mode that a self-written test cannot catch, because a plausible-looking wrong blend
 * passes any test whose expected values came from the same head that wrote the blend.
 *
 * TOLERANCE. 1e-6, as the spec sets it. Java and Kotlin do the same IEEE-754 single-precision
 * operations here, so the expected difference between a faithful transcription and the table is 0;
 * 1e-6 is roughly eight ulp of the 0..1 range, which absorbs FMA contraction (Kotlin/Native and
 * the JVM's JIT may fuse a multiply-add differently) without being wide enough to hide a
 * transcription error. Anything at the epsilon corners — `b / max(s, 1e-5)` — is where a real
 * error would hide, and at 1e-6 an error there would still be a million times too big.
 */
class BlendParityTest {

    private val out = FloatArray(3)
    private val scratch = FloatArray(3)
    private val b = FloatArray(3)
    private val s = FloatArray(3)

    // ── 1. every golden row, every mode ──────────────────────────────────────────

    @Test
    fun everyGoldenRowMatchesTheStudioForEveryMode() {
        var checked = 0
        var worst = 0f
        var worstWhere = ""
        for (pair in 0 until BlendGolden.PAIR_COUNT) {
            for (ch in 0..2) {
                b[ch] = BlendGolden.BS[pair * 6 + ch]
                s[ch] = BlendGolden.BS[pair * 6 + 3 + ch]
            }
            for (mode in 0 until BlendGolden.MODE_COUNT) {
                BlendRgb.blendRgb(mode, b, s, out, scratch)
                for (ch in 0..2) {
                    val expected = BlendGolden.expected(mode, pair, ch)
                    val d = kotlin.math.abs(out[ch] - expected)
                    if (d > worst || worstWhere.isEmpty()) {
                        worst = d
                        worstWhere = "${BlendGolden.NAMES[mode]} b=${b[0]},${b[1]},${b[2]} " +
                            "s=${s[0]},${s[1]},${s[2]} ch=$ch"
                    }
                    if (!(d <= tolerance(expected))) {
                        fail(
                            "Joy Brush's ${BlendGolden.NAMES[mode]} disagrees with the Studio.\n" +
                                "  backdrop ${b[0]}, ${b[1]}, ${b[2]}\n" +
                                "  source   ${s[0]}, ${s[1]}, ${s[2]}\n" +
                                "  channel  $ch\n" +
                                "  Studio   $expected\n" +
                                "  ours     ${out[ch]}\n" +
                                "  off by   $d (allowed ${tolerance(expected)})\n" +
                                "  pair $pair, mode $mode\n" +
                                "If the Studio's equations changed, regenerate the table with\n" +
                                "  bash tools/gen_blend_golden.sh\n" +
                                "If they did not, this transcription is wrong.",
                        )
                    }
                    checked++
                }
            }
        }
        assertEquals(
            BlendGolden.PAIR_COUNT * BlendGolden.MODE_COUNT * 3, checked,
            "the table must be walked whole, or a skipped block of rows is an untested block",
        )
        assertTrue(
            worst <= tolerance(1f),
            "largest disagreement over all $checked values was $worst (worst case: $worstWhere)",
        )
    }

    /**
     * The mode LIST, checked against the Studio's rather than against itself.
     *
     * `BlendRgb.STUDIO_MODES` is a hand-written transcription of `BlendModes.ALL`, and the whole
     * point of Decision 1 in the spec was to notice a Studio mode the list missed. This is the
     * check that would notice: the generated table carries `BlendModes.ALL` verbatim, so any
     * disagreement is a mode Joy Brush would refuse to composite.
     */
    @Test
    fun everyStudioModeIsCarriedOverExactlyOnceAtItsOwnCode() {
        assertEquals(
            BlendGolden.MODE_COUNT, BlendRgb.STUDIO_MODES.size,
            "the Studio has ${BlendGolden.MODE_COUNT} modes; Joy Brush must carry all of them",
        )
        assertEquals(BlendGolden.NAMES, BlendRgb.STUDIO_MODES)
        for (code in BlendGolden.NAMES.indices) {
            assertEquals(
                code, BlendRgb.studioCodeOf(BlendGolden.NAMES[code]),
                "${BlendGolden.NAMES[code]} is mode code $code in the Studio",
            )
        }
        assertEquals(
            BlendGolden.MODE_COUNT, BlendRgb.STUDIO_MODES.toSet().size,
            "a duplicated name would leave a mode unreachable",
        )
    }

    // ── 2. the table is the shape the spec asked for, and not only that ───────────

    @Test
    fun theTableCoversTheSpecCasesAndTheCasesTheSpecCasesMiss() {
        assertEquals(400, BlendGolden.RANDOM_PAIRS, "the spec's fixed-seed random half")
        assertEquals(27, BlendGolden.CORNER_SELF_PAIRS, "{0, 0.5, 1}^3 as (t, t)")
        assertEquals(427, BlendGolden.SPEC_PAIRS, "400 + 27, the rows the spec asked for")
        assertEquals(
            BlendGolden.PAIR_COUNT,
            BlendGolden.SPEC_PAIRS + BlendGolden.CORNER_CROSS_PAIRS + BlendGolden.OUT_OF_RANGE_PAIRS,
        )
        assertEquals(20260929L, BlendGolden.SEED, "the seed is part of the table's contract")

        // Rows [0, 427) really are the spec's two groups: 400 uniform pairs then 27 (t, t).
        for (pair in 0 until BlendGolden.RANDOM_PAIRS) {
            for (ch in 0..2) {
                assertTrue(BlendGolden.BS[pair * 6 + ch] in 0f..1f, "random pair $pair is out of range")
                assertTrue(BlendGolden.BS[pair * 6 + 3 + ch] in 0f..1f, "random pair $pair is out of range")
            }
        }
        val corner = setOf(0f, 0.5f, 1f)
        for (pair in BlendGolden.RANDOM_PAIRS until BlendGolden.SPEC_PAIRS) {
            for (ch in 0..2) {
                assertTrue(BlendGolden.BS[pair * 6 + ch] in corner, "corner pair $pair")
                assertEquals(BlendGolden.BS[pair * 6 + ch], BlendGolden.BS[pair * 6 + 3 + ch])
            }
        }
        // The 27 corner triples must each appear, or "the 27 corner cases" is a claim, not a fact.
        val seen = HashSet<String>()
        for (pair in BlendGolden.RANDOM_PAIRS until BlendGolden.SPEC_PAIRS) {
            seen.add("${BlendGolden.BS[pair * 6]},${BlendGolden.BS[pair * 6 + 1]},${BlendGolden.BS[pair * 6 + 2]}")
        }
        assertEquals(27, seen.size)
    }

    /**
     * The results really are UNCLAMPED, which is the contract and the thing the extra rows exist
     * for. If this fails, `blendRgb` has started clamping inside the blend term: every exporter
     * would then clip in the wrong place, and every golden row would still pass, because with
     * 0..1 input every one of the 26 modes lands in 0..1 anyway.
     */
    @Test
    fun theStudioReturnsUnclampedResultsAndSoMustWe() {
        var above = 0
        var below = 0
        for (pair in BlendGolden.FIRST_OUT_OF_RANGE_PAIR until BlendGolden.PAIR_COUNT) {
            for (mode in 0 until BlendGolden.MODE_COUNT) {
                for (ch in 0..2) {
                    val v = BlendGolden.expected(mode, pair, ch)
                    if (v > 1f) above++
                    if (v < 0f) below++
                }
            }
        }
        assertTrue(above > 100, "expected plenty of values above 1 among the out-of-range rows, saw $above")
        assertTrue(below > 100, "expected plenty of values below 0 among the out-of-range rows, saw $below")

        // And the one named case, so a reader can see the numbers.
        // SCREEN(b = 2, s = 0) = 1 - (1 - 2)(1 - 0) = 2.
        b[0] = 2f; b[1] = 2f; b[2] = 2f
        s[0] = 0f; s[1] = 0f; s[2] = 0f
        BlendRgb.blendRgb(BlendRgb.studioCodeOf("SCREEN"), b, s, out, scratch)
        assertEquals(2f, out[0], 1e-6f, "SCREEN must not clip its own result")
    }

    // ── 3. the eight original modes must not move ─────────────────────────────────

    /**
     * Spec test 3, as a positive check rather than only "the old tests still pass".
     *
     * `render.Blend` is asked for its term by running its own composite with `sa = da = 1`, which
     * reduces the W3C formula to `0 + 1*B + 0` — exactly `B`, in float, with no approximation.
     * If one of these eight ever disagreed with the Studio's equation, that is a FINDING for the
     * Lead (the Studio and Joy Brush already disagreed, and the old 7 were written by hand) — so
     * this test is expected to keep passing and would be reporting a real discovery if it did not.
     */
    @Test
    fun theEightOriginalModesStillAgreeWithTheRenderer() {
        // The seven Joy Brush already had, named explicitly rather than as
        // `entries.filter { it != ERASE_BELOW }`. That filter was right when the enum had eight
        // entries and silently became "all twenty-six Studio modes" when JB-2.20a appended nineteen
        // — a test that keeps passing while quietly testing something else, which is the failure
        // mode this whole task exists to prevent. Naming them also says what the test is FOR: the
        // old renderer is unchanged by the twenty new modes.
        val shared = listOf(
            BlendMode.NORMAL, BlendMode.MULTIPLY, BlendMode.SCREEN, BlendMode.OVERLAY,
            BlendMode.ADD, BlendMode.DARKEN, BlendMode.LIGHTEN,
        )
        assertEquals(7, shared.size, "the Studio has no ERASE_BELOW, so seven of the eight are shared")
        // 27 = the eight Joy Brush had (seven shared + ERASE_BELOW) plus the nineteen the Studio
        // brought (JB-2.20a, R23). Pinning the arithmetic rather than a bare 27 means a mode added or
        // removed on either side of the line has to be counted, not just tolerated.
        assertEquals(
            8 + 19,
            BlendMode.entries.size,
            "the enum is the eight Joy Brush had plus the nineteen the Studio brought",
        )

        var checked = 0
        for (pair in 0 until BlendGolden.PAIR_COUNT) {
            for (ch in 0..2) {
                val bv = BlendGolden.BS[pair * 6 + ch]
                val sv = BlendGolden.BS[pair * 6 + 3 + ch]
                for (mode in shared) {
                    val viaRenderer = renderTerm(mode, bv, sv)
                    BlendRgb.blendRgb(mode, floatArrayOf(bv, bv, bv), floatArrayOf(sv, sv, sv), out, scratch)
                    if (kotlin.math.abs(out[0] - viaRenderer) > tolerance(viaRenderer)) {
                        fail(
                            "${mode.name} moved: render.Blend gives $viaRenderer for b=$bv s=$sv, " +
                                "BlendRgb gives ${out[0]}",
                        )
                    }
                    checked++
                }
            }
        }
        assertEquals(BlendGolden.PAIR_COUNT * 3 * 7, checked)
    }

    /**
     * [render.Blend.apply] with both alphas at 1. The premultiplied out is
     * `sa(1-da)Cs + sa*da*B + (1-sa)da*Cb` = `B`, so this reads the renderer's own term without
     * duplicating it — which is the whole point: a second copy of the eight equations in the test
     * would be a second thing to be wrong.
     */
    private fun renderTerm(mode: BlendMode, b: Float, s: Float): Float {
        val src = floatArrayOf(s, s, s, 1f)
        val dst = floatArrayOf(b, b, b, 1f)
        val o = FloatArray(4)
        Blend.apply(mode, src, dst, o)
        return o[0]
    }

    // ── 4. the two doors agree, and an unknown mode is refused ────────────────────

    @Test
    fun theBlendModeDoorAndTheCodeDoorAgree() {
        for (mode in BlendMode.entries) {
            if (mode == BlendMode.ERASE_BELOW) continue
            b[0] = 0.2f; b[1] = 0.6f; b[2] = 0.9f
            s[0] = 0.7f; s[1] = 0.4f; s[2] = 0.1f
            val byName = BlendRgb.blendRgb(mode, b, s)
            val byCode = BlendRgb.blendRgb(BlendRgb.codeOf(mode), b, s)
            assertEquals(byCode[0], byName[0], 0f, "${mode.name}: the doors disagree")
            assertEquals(byCode[1], byName[1], 0f, "${mode.name}: the doors disagree")
            assertEquals(byCode[2], byName[2], 0f, "${mode.name}: the doors disagree")
        }
    }

    @Test
    fun eraseBelowIsJoyBrushsOwnAndHasNoBlendTerm() {
        assertFailsWith<IllegalArgumentException> { BlendRgb.studioCodeOf("ERASE_BELOW") }
        assertFailsWith<IllegalArgumentException> { BlendRgb.codeOf(BlendMode.ERASE_BELOW) }
    }

    @Test
    fun anUnknownModeNameIsRefusedRatherThanBecomingNormal() {
        // The Studio falls back to NORMAL for an unreadable mode, and Joy Brush must not: a layer
        // that quietly composites as NORMAL is a painting that changed without anybody being told.
        assertFailsWith<IllegalArgumentException> { BlendRgb.studioCodeOf("HOLOGRAM") }
    }

    @Test
    fun aCodeOutsideTheStudioRangeYieldsTheSourceLikeTheStudioDoes() {
        b[0] = 0.25f; b[1] = 0.5f; b[2] = 0.75f
        s[0] = 0.9f; s[1] = 0.1f; s[2] = 0.4f
        for (code in listOf(-1, 26, 99)) {
            BlendRgb.blendRgb(code, b, s, out, scratch)
            assertEquals(s[0], out[0], 0f, "code $code")
            assertEquals(s[1], out[1], 0f, "code $code")
            assertEquals(s[2], out[2], 0f, "code $code")
        }
    }

    private fun tolerance(expected: Float): Float = 1e-6f * maxOf(1f, kotlin.math.abs(expected))
}
