package cc.joycreator.joybrush.core.fill

import cc.joycreator.joybrush.core.doc.RectPx
import cc.joycreator.joybrush.core.paint.Tiles
import cc.joycreator.joybrush.core.select.SelectionMask
import cc.joycreator.joybrush.core.shape.Pt
import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.nextDown
import kotlin.math.nextUp
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * JB-2.07a — painting a [SelectionMask] through a layer's premultiplied tiles. The raster maths
 * of the fill pen (LEAD_RULINGS R21: the fill pen is a brush, not a tool; this is what draws it)
 * and of the tap fill, which differs only in where the mask came from.
 *
 * ## WHERE THE EXPECTED VALUES COME FROM, which is the point of this file
 *
 * Four sources, and they are not interchangeable:
 *
 *  1. [theGoldenTableAgreesWithAnIndependentExactRationalModel] — 3123 rows generated by a second
 *     implementation in exact rational arithmetic (`fractions.Fraction`, never binary floating
 *     point) that never saw this module's source. This is the one that CAN disagree with a bug,
 *     because a bug and a hand-derived number come from the same head. Everything else here is a
 *     check on the table's own claims.
 *  2. [theWholeLassoAgreesWithTheOnePixelFunctionPixelForPixel] — the invariant that keeps
 *     [MaskPaint.apply] (the tile walk) and [MaskPaint.pixel] (the arithmetic) from drifting
 *     apart. The golden table only sees `pixel`, so without this a change to `apply` alone would
 *     be invisible to it.
 *  3. Invariants computed a DIFFERENT WAY — the painted area against the mask's own coverage sum,
 *     a shape against its half turn, the second pass of a solid fill. Each has an answer that
 *     does not require knowing the formula.
 *  4. Hand-derived values, and there are only a handful, each with its derivation in a comment
 *     beside it — Lead ruling R9's standing rule: an expected value may be changed only with its
 *     derivation written down, never to make a run go green.
 */
class MaskPaintTest {

    // ── the golden table ──────────────────────────────────────────────────────────

    @Test
    fun theGoldenTableAgreesWithAnIndependentExactRationalModel() {
        assertEquals(
            MaskPaintGolden.EXPECTED_SIZE, MaskPaintGolden.ROWS.size,
            "the table is the evidence, and its three parts must all still be joined in",
        )
        assertTrue(MaskPaintGolden.ROWS.size > 3000, "the table is the evidence; do not shrink it")
        val out = IntArray(4)
        var checked = 0
        for (row in MaskPaintGolden.ROWS) {
            pixel(row.mode, row.argb, row.opacity, row.coverage, row.dest, out)
            for (c in 0..3) {
                assertEquals(
                    row.expect[c],
                    out[c],
                    "channel $c of ${row.mode} argb=0x${row.argb.toUInt().toString(16)} " +
                        "opacity=${row.opacity} coverage=${row.coverage} " +
                        "dest=${row.dest.joinToString(",")} — the exact-rational model says " +
                        "${row.expect.joinToString(",")}, MaskPaint said ${out.joinToString(",")}",
                )
            }
            checked++
        }
        assertEquals(MaskPaintGolden.ROWS.size, checked)
    }

    /**
     * The table covers all three modes and both ends of the opacity and coverage ranges. If a
     * future edit narrows any of them the table quietly stops being evidence, so the coverage is
     * asserted rather than assumed.
     */
    @Test
    fun theTableCoversEveryModeAndTheEndsOfEveryRange() {
        assertEquals(
            MaskPaintMode.entries.toSet(),
            MaskPaintGolden.ROWS.map { it.mode }.toSet(),
            "a mode with no rows is an untested mode",
        )
        val coverages = MaskPaintGolden.ROWS.map { it.coverage }.toSet()
        assertEquals(0, coverages.min(), "coverage 0 — the mask misses the pixel")
        assertEquals(255, coverages.max(), "coverage 255 — solid")
        // Not an exact count: the table's row count is the generator's business, and asserting a
        // number here would mean editing this test every time a row is added. What has to hold is
        // that solid coverage is exercised across every colour and every mode, which is
        // `>= 3 modes * a spread of colours`.
        assertTrue(
            MaskPaintGolden.ROWS.count { it.coverage == 255 } > 200,
            "solid coverage must be exercised across every mode and a spread of colours",
        )
        assertTrue(
            MaskPaintGolden.ROWS.any { it.opacity == 0f }, "opacity 0")
        assertTrue(
            MaskPaintGolden.ROWS.any { it.opacity == 1f }, "opacity 1")
        assertTrue(
            MaskPaintGolden.ROWS.any { row -> row.dest.all { c -> c == 0 } },
            "the empty destination — a fill onto blank paper is the common case",
        )
        assertTrue(
            MaskPaintGolden.ROWS.any { row -> row.dest[3] == 255 && row.dest[0] == 255 },
            "the opaque destination — BEHIND over it is a no-op and the table says what that is",
        )
        // The clamp's only reason to exist. Without a non-premultiplied destination in the table
        // the colour <= alpha clamp could be deleted and the table would stay green.
        assertTrue(
            MaskPaintGolden.ROWS.any { row -> row.dest[0] > row.dest[3] },
            "a destination with colour > alpha, which is what the premultiplied clamp is for",
        )
        assertTrue(
            MaskPaintGolden.ROWS.all { row -> row.expect[0] <= row.expect[3] },
            "every expected pixel is premultiplied, including the ones that started un-premultiplied",
        )
    }

    // ── apply is pixel, everywhere ────────────────────────────────────────────────

    /**
     * THE BRIDGE TEST, and the reason [MaskPaint.pixel] is a public door at all.
     *
     * The golden table tests the arithmetic; it cannot see the tile walk. So walk REAL masks —
     * a lasso with antialiased edges, a shape with a hole, shapes across both tile seams, a
     * shape at negative coordinates — and check every pixel of every returned tile against the
     * one-pixel function. Every way the walk can be wrong (a coverage read from the wrong tile, a
     * row stride of 256 instead of 256*4, a premultiplied/straight mix-up) moves a pixel, and this
     * moves all of them.
     *
     * The destination VARIES with position, so a walk that reads the wrong pixel's backdrop still
     * fails here; a constant backdrop would let a whole class of indexing bug through.
     */
    @Test
    fun theWholeLassoAgreesWithTheOnePixelFunctionPixelForPixel() {
        for (mask in shapes()) {
            assertFalse(mask.isEmpty, "a test shape that rasterised to nothing tests nothing")
            for (mode in MaskPaintMode.entries) {
                for (argb in listOf(0xFFFF0000.toInt(), 0xFF3399CC.toInt(), 0xFF000000.toInt())) {
                    for (opacity in listOf(1f, 0.5f, 0.25f)) {
                        val layer = rampLayer(mask)
                        val changed = MaskPaint.apply(layer, mask, argb, opacity, mode)
                        for (key in changed.keys) {
                            val tile = changed[key] ?: continue
                            val cov = assertNotNull(mask.tile(key), "changed tile $key has no mask")
                            val tx = Tiles.tx(key) * Tiles.SIZE
                            val ty = Tiles.ty(key) * Tiles.SIZE
                            for (row in 0 until Tiles.SIZE) {
                                for (col in 0 until Tiles.SIZE) {
                                    val at = (row * Tiles.SIZE + col) * 4
                                    val c = cov[row * Tiles.SIZE + col].toInt() and 0xFF
                                    val x = tx + col
                                    val y = ty + row
                                    val d = rampPixel(x, y)
                                    if (c == 0) {
                                        assertContentEquals(
                                            ByteArray(4) { d[it].toByte() },
                                            tile.copyOfRange(at, at + 4),
                                            "mode $mode: ($x,$y) is not covered, so the destination " +
                                                "must be carried through the tile byte for byte",
                                        )
                                        continue
                                    }
                                    val out = pixel(mode, argb, opacity, c, d, IntArray(4))
                                    for (ch in 0..3) {
                                        assertEquals(
                                            out[ch],
                                            tile[at + ch].toInt() and 0xFF,
                                            "mode $mode argb=0x${argb.toUInt().toString(16)} " +
                                                "opacity=$opacity pixel ($x,$y) coverage=$c channel $ch",
                                        )
                                    }
                                    pixelsWalked++
                                }
                            }
                        }
                    }
                }
            }
        }
        assertTrue(
            pixelsWalked > 200_000,
            "only $pixelsWalked covered pixels walked; too few for this to be evidence",
        )
    }

    private var pixelsWalked = 0

    // ── invariants computed a different way ───────────────────────────────────────

    /**
     * AREA, NOT FORMULA. A solid fill onto an empty layer paints an alpha equal to the coverage
     * at every pixel, so the SUM of the alpha of a filled shape must equal the SUM of the mask's
     * coverage over the same box — a number computed by a completely different route (a summation
     * over `SelectionMask.coverage`) and never through the blend arithmetic.
     *
     * This is the check that catches a stride or an off-by-one in the tile walk, because those
     * move the total far more visibly than they move any one pixel.
     */
    @Test
    fun thePaintedAreaEqualsTheSelectedArea() {
        val box = RectPx(20, 30, 200, 140)
        val mask = SelectionMask.rect(box)
        val selected = coverageSum(mask, box)
        assertEquals(200L * 140L * 255L, selected, "SelectionMask.rect is exactly 255 inside, so this is exact")
        for (opacity in listOf(1f, 0.5f, 0.25f, 0.125f)) {
            val painted = totalAlpha(
                MaskPaint.apply(emptyMap(), mask, 0xFF204080.toInt(), opacity, MaskPaintMode.FILL),
            )
            val expected = selected.toDouble() * opacity
            if (opacity == 1f) {
                assertEquals(selected, painted, "at full opacity the painted alpha IS the coverage")
            } else {
                // Each pixel's alpha is round(255 * (c/255) * o) = round(c*o), so the total is
                // within half a unit per painted pixel of `selected * o`. The bound is 200*140/2
                // pixels, which is loose but not so loose that a stride error survives it.
                assertTrue(
                    abs(painted - expected) <= (box.w.toLong() * box.h.toLong()),
                    "opacity $opacity: painted alpha total $painted, expected about ${expected.toInt()}",
                )
            }
        }
    }

    /**
     * SYMMETRY. A square and the same square reflected through the origin must paint the same
     * total alpha, and — because the arithmetic is per pixel and knows nothing about shapes — the
     * same answer at the pixel that maps onto the pixel that maps.
     *
     * The reflection is exact for a square, so no area correction is needed; the destination
     * ramp is a function of position, so this is a real check rather than two equal constants.
     */
    @Test
    fun aShapeAndItsMirrorPaintTheSameAmount() {
        val a = SelectionMask.polygon(
            listOf(Pt(20.0, 30.0), Pt(180.0, 30.0), Pt(180.0, 140.0), Pt(20.0, 140.0)),
        )
        val b = SelectionMask.polygon(
            listOf(Pt(-180.0, -140.0), Pt(-20.0, -140.0), Pt(-20.0, -30.0), Pt(-180.0, -30.0)),
        )
        // The premise, pinned first: this reflection is exact for a square, so a and b really do
        // have the same coverage multiset. Without it, an equality below would be vacuous.
        assertEquals(
            coverageSum(a, RectPx(20, 30, 160, 110)),
            coverageSum(b, RectPx(-180, -140, 160, 110)),
            "the two squares must be reflections of each other, or the equality below means nothing",
        )
        for (mode in MaskPaintMode.entries) {
            for (opacity in listOf(1f, 0.6f)) {
                val layer = rampLayer(a) + rampLayer(b)
                val ca = MaskPaint.apply(layer, a, 0xFF00FF00.toInt(), opacity, mode)
                val cb = MaskPaint.apply(layer, b, 0xFF00FF00.toInt(), opacity, mode)
                assertEquals(
                    totalAlpha(ca), totalAlpha(cb),
                    "mode $mode opacity $opacity: reflecting a shape changed the painted total, and " +
                        "the per-pixel arithmetic cannot know a shape from its reflection",
                )
                assertFalse(ca.isEmpty(), "the square painted nothing at all")
            }
        }
    }

    /**
     * A SECOND PASS OF A FULLY OPAQUE FILL IS A COMPLETE NO-OP — reported as an EMPTY change set,
     * not as equal bytes.
     *
     * This is the same property twice, and both halves matter. Source-over with `a = 1` REPLACES,
     * and destination-over with `room = 0` adds nothing, so the second pass produces bytes
     * identical to the first's. And Decision 2 says identical bytes are NOT reported — so the
     * second pass records no undo step. A fill that accumulated instead would read as a fill that
     * goes darker every time a person undoes and redoes it, which is the classic sign of a blend
     * compositing onto itself rather than replacing.
     */
    @Test
    fun aSecondPassOfAnOpaqueFillReportsNothingAtAll() {
        // 300 x 300 from the origin crosses BOTH seams, so four tiles: a walk that counted two
        // would already be wrong about which tiles a shape touches.
        val mask = SelectionMask.rect(RectPx(0, 0, 300, 300))
        for (mode in listOf(MaskPaintMode.FILL, MaskPaintMode.BEHIND)) {
            val once = MaskPaint.apply(emptyMap(), mask, 0xFFEE8800.toInt(), 1f, mode)
            assertEquals(4, once.size, "mode $mode: a 300 x 300 square at the origin is four tiles")
            val twice = MaskPaint.apply(once.asLayer(), mask, 0xFFEE8800.toInt(), 1f, mode)
            assertTrue(
                twice.isEmpty(),
                "mode $mode: an opaque fill over its own result changes nothing, so nothing is " +
                    "reported. Got keys ${twice.keys}",
            )
        }
    }

    /**
     * ERASE TWICE IS ONCE, and it is measured rather than asserted. `D*(1-a)` at `a = 1` empties
     * the tile on the first pass and the second pass finds nothing there, so it reports nothing:
     * an erase over already-empty paper costs no undo step.
     */
    @Test
    fun aSecondEraseOverEmptyPaperRecordsNothing() {
        val mask = SelectionMask.rect(RectPx(0, 0, 64, 64))
        val painted = MaskPaint.apply(emptyMap(), mask, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL)
        val erased = MaskPaint.apply(painted.asLayer(), mask, 0, 1f, MaskPaintMode.ERASE)
        assertEquals(
            listOf(Tiles.key(0, 0)), erased.keys.toList(),
            "erasing a solid fill from a solid fill empties exactly the tile it painted",
        )
        assertNull(erased[Tiles.key(0, 0)], "an emptied tile is a DELETE (null), not a zero tile")
        // The same call again, from the same starting layer, is the same change set.
        assertContentEquals(
            erased.keys.toList(),
            MaskPaint.apply(painted.asLayer(), mask, 0, 1f, MaskPaintMode.ERASE).keys.toList(),
        )
    }

    /**
     * THE OPPOSITE, and it is why Decision 2 is not "drop empty tiles and be done". A
     * [MaskPaintMode.BEHIND] under fully opaque paint changes nothing and so is not in the answer
     * at all. Dropping the tile instead would DELETE a tile full of somebody's drawing, which is
     * the worst thing this function could do.
     */
    @Test
    fun behindFullyOpaquePaintReportsNothingRatherThanDeletingIt() {
        val mask = SelectionMask.rect(RectPx(0, 0, 64, 64))
        val original = solidTile(9, 0, 0, 255)
        val layer = mapOf(Tiles.key(0, 0) to original)
        val changed = MaskPaint.apply(layer, mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.BEHIND)
        assertTrue(changed.isEmpty(), "a BEHIND under opaque paint is a no-op, so it is not reported")
        assertContentEquals(
            original, layer.getValue(Tiles.key(0, 0)),
            "the caller's tile was written to, which would also break the undo snapshot",
        )
    }

    // ── the spec's seven tests ────────────────────────────────────────────────────

    /** Spec test 1: FILL a 10 x 10 square in opaque red on an empty layer -> 100 red pixels. */
    @Test
    fun fillASquareMaskInOpaqueRedOnAnEmptyLayer() {
        val mask = SelectionMask.rect(RectPx(5, 5, 10, 10))
        val changed = MaskPaint.apply(emptyMap(), mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.FILL)
        assertEquals(1, changed.size, "one 10 x 10 square is one tile")
        val tile = assertNotNull(changed[Tiles.key(0, 0)])
        var red = 0
        for (y in 0 until Tiles.SIZE) {
            for (x in 0 until Tiles.SIZE) {
                val at = (y * Tiles.SIZE + x) * 4
                if (mask.coverage(x, y) == 0) {
                    assertEquals(0, tile[at + 3].toInt() and 0xFF, "($x,$y) is outside the mask")
                    continue
                }
                assertEquals(255, tile[at].toInt() and 0xFF, "($x,$y) red")
                assertEquals(0, tile[at + 1].toInt() and 0xFF, "($x,$y) green")
                assertEquals(0, tile[at + 2].toInt() and 0xFF, "($x,$y) blue")
                assertEquals(255, tile[at + 3].toInt() and 0xFF, "($x,$y) alpha")
                red++
            }
        }
        assertEquals(100, red, "10 x 10 is 100 px, and SelectionMask.rect is exactly 255 inside")
    }

    /**
     * Spec test 2: FILL at opacity 0.5 over opaque blue -> (128, 0, 128, 255).
     *
     * DERIVATION. Opaque blue is premultiplied (0, 0, 255, 255). Red at `a = 0.5` gives the
     * premultiplied source (127.5, 0, 0, 127.5), and FILL is `S + D*(1-a)` = (127.5, 0, 127.5,
     * 127.5 + 127.5) = (127.5, 0, 127.5, 255). Rounded half up: (128, 0, 128, 255). The alpha is
     * exactly 255 because an opaque backdrop under source-over stays opaque.
     */
    @Test
    fun fillAtHalfOpacityOverOpaqueBlue() {
        val mask = SelectionMask.rect(RectPx(0, 0, 8, 8))
        val layer = mapOf(Tiles.key(0, 0) to solidTile(0, 0, 255, 255))
        val tile = assertNotNull(
            MaskPaint.apply(layer, mask, 0xFFFF0000.toInt(), 0.5f, MaskPaintMode.FILL)[Tiles.key(0, 0)],
        )
        for (y in 0 until 8) {
            for (x in 0 until 8) {
                val at = (y * Tiles.SIZE + x) * 4
                val got = (0..3).map { tile[at + it].toInt() and 0xFF }
                assertTrue(
                    abs(got[0] - 128) <= 1 && got[1] == 0 && abs(got[2] - 128) <= 1,
                    "($x,$y) expected about (128, 0, 128, 255) +/-1, got ${got.joinToString(",")}",
                )
                assertEquals(255, got[3], "($x,$y) alpha stays opaque: 127.5 + 127.5 is 255")
            }
        }
    }

    /**
     * Spec test 3: ERASE the same square out of an opaque layer -> those pixels 0; ERASE a whole
     * tile's area -> that tile is returned as null.
     */
    @Test
    fun eraseASquareOutOfAnOpaqueLayer() {
        val mask = SelectionMask.rect(RectPx(0, 0, 10, 10))
        val layer = mapOf(Tiles.key(0, 0) to solidTile(0, 0, 255, 255))
        val tile = assertNotNull(
            MaskPaint.apply(layer, mask, 0, 1f, MaskPaintMode.ERASE)[Tiles.key(0, 0)],
            "a partial erase is an edit, not a delete",
        )
        for (y in 0 until 64) {
            for (x in 0 until 64) {
                val at = (y * Tiles.SIZE + x) * 4
                val inside = x < 10 && y < 10
                // Outside the square the tile is the opaque blue it started as, byte for byte.
                val want = if (inside) listOf(0, 0, 0, 0) else listOf(0, 0, 255, 255)
                for (c in 0..3) {
                    assertEquals(
                        want[c], tile[at + c].toInt() and 0xFF,
                        "($x,$y) channel $c (inside=$inside)",
                    )
                }
            }
        }
        val whole = MaskPaint.apply(
            layer, SelectionMask.rect(RectPx(0, 0, 256, 256)), 0, 1f, MaskPaintMode.ERASE,
        )
        assertEquals(listOf(Tiles.key(0, 0)), whole.keys.toList())
        assertNull(whole[Tiles.key(0, 0)], "a tile erased entirely comes back as null (delete it)")
    }

    /**
     * Spec test 4: BEHIND over a layer with a black 1-px line through the square — the line is
     * untouched, the rest is red, and a soft line-edge pixel gets red only in its transparent
     * share.
     *
     * DERIVATION. The line pixel is opaque black (0, 0, 0, 255), so `room = 1 - 255/255 = 0` and
     * BEHIND adds `S*0`: the line is untouched. Every other pixel in the square is transparent
     * (`room = 1`) and becomes the source exactly — (255, 0, 0, 255) for red.
     *
     * THE SOFT EDGE, which is not a special case. A half-covered line pixel (0, 0, 0, 128) has
     * `room = 1 - 128/255 = 127/255`, so the red landing there is `255 * 127/255 = 127`
     * premultiplied and the new alpha is `128 + 255*127/255 = 255`. That is "red only in the
     * transparent share": 127/255 of the pixel's capacity was free, and all of it is now red.
     */
    @Test
    fun behindLeavesTheLineAloneAndColoursTheRest() {
        val mask = SelectionMask.rect(RectPx(0, 0, 16, 16))
        val layer = ByteArray(Tiles.SIZE * Tiles.SIZE * 4)
        for (x in 0 until 16) {
            var at = (8 * Tiles.SIZE + x) * 4
            layer[at + 3] = 255.toByte()
            at = (9 * Tiles.SIZE + x) * 4
            layer[at + 3] = 128.toByte()
        }
        val tile = assertNotNull(
            MaskPaint.apply(
                mapOf(Tiles.key(0, 0) to layer), mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.BEHIND,
            )[Tiles.key(0, 0)],
        )
        for (x in 0 until 16) {
            for (c in 0..3) {
                val solid = (8 * Tiles.SIZE + x) * 4 + c
                assertEquals(layer[solid].toInt() and 0xFF, tile[solid].toInt() and 0xFF, "line ($x,8) channel $c")
            }
            val soft = (9 * Tiles.SIZE + x) * 4
            assertEquals(127, tile[soft].toInt() and 0xFF, "soft edge red: 255 * 127/255")
            assertEquals(0, tile[soft + 1].toInt() and 0xFF, "soft edge green")
            assertEquals(0, tile[soft + 2].toInt() and 0xFF, "soft edge blue")
            assertEquals(255, tile[soft + 3].toInt() and 0xFF, "soft edge alpha: 128 + 127")
        }
        for (y in 0 until 8) {
            for (x in 0 until 16) {
                val at = (y * Tiles.SIZE + x) * 4
                assertEquals(255, tile[at].toInt() and 0xFF, "($x,$y) red")
                assertEquals(255, tile[at + 3].toInt() and 0xFF, "($x,$y) alpha")
            }
        }
    }

    /**
     * Spec test 5: nothing changes -> an empty result. The first three are the spec's own cases;
     * the fourth is the one worth adding, because a NaN opacity is 1 and an opaque fill over
     * opaque paper is therefore NOT empty — a check that would have passed for the wrong reason
     * if the NaN had silently become 0.
     */
    @Test
    fun nothingChangingReturnsNothing() {
        val mask = SelectionMask.rect(RectPx(0, 0, 32, 32))
        val opaque = mapOf(Tiles.key(0, 0) to solidTile(0, 0, 0, 255))
        assertTrue(
            MaskPaint.apply(emptyMap(), mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.ERASE).isEmpty(),
            "ERASE on empty canvas: the tile is already all zero, so nothing changes",
        )
        assertTrue(
            MaskPaint.apply(opaque, mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.BEHIND).isEmpty(),
            "BEHIND under fully opaque paint",
        )
        assertTrue(
            MaskPaint.apply(opaque, mask, 0xFFFF0000.toInt(), 0f, MaskPaintMode.FILL).isEmpty(),
            "an opacity of 0 is a no-op in every mode",
        )
        assertFalse(
            MaskPaint.apply(opaque, mask, 0xFFFF0000.toInt(), Float.NaN, MaskPaintMode.FILL).isEmpty(),
            "a NaN opacity is 1, and white over black changes black — so this is NOT empty. If it " +
                "were, the NaN would have become 0 and this test would be passing for the wrong reason",
        )
    }

    /**
     * Spec test 6: a lasso crossing a tile seam at x = 256 paints both tiles with no seam artefact.
     *
     * The check is a COLOUR CONTINUITY check, not a "both keys are present" check: the two pixels
     * either side of the seam are one pixel apart in the document, so their alpha must be equal.
     * A walk that mis-strided by one byte, or read the wrong tile's coverage, shows here and
     * nowhere else in the suite.
     */
    @Test
    fun aLassoOverATileSeamPaintsBothTilesWithNoSeam() {
        val mask = SelectionMask.rect(RectPx(250, 20, 12, 40))
        val changed = MaskPaint.apply(emptyMap(), mask, 0xFF40C0FF.toInt(), 1f, MaskPaintMode.FILL)
        assertEquals(2, changed.size, "x = 250..261 crosses 256, so two tiles are in play")
        val left = assertNotNull(changed[Tiles.key(0, 0)])
        val right = assertNotNull(changed[Tiles.key(1, 0)])
        for (y in 20 until 60) {
            val l = (y * Tiles.SIZE + 255) * 4 + 3
            val r = (y * Tiles.SIZE) * 4 + 3
            assertEquals(255, left[l].toInt() and 0xFF, "row $y, x = 255")
            assertEquals(255, right[r].toInt() and 0xFF, "row $y, x = 256")
        }
        // And the shape is pixel-exact either side of the seam: a rect has no antialiasing, so
        // x = 249 and x = 262 are untouched in their own tiles and x = 255 and x = 256 are solid.
        assertEquals(0, left[(20 * Tiles.SIZE + 249) * 4 + 3].toInt() and 0xFF, "x = 249 is outside")
        assertEquals(255, left[(20 * Tiles.SIZE + 255) * 4 + 3].toInt() and 0xFF, "x = 255 is inside")
        assertEquals(255, right[(20 * Tiles.SIZE) * 4 + 3].toInt() and 0xFF, "x = 256 is inside")
        assertEquals(0, right[(20 * Tiles.SIZE + 6) * 4 + 3].toInt() and 0xFF, "x = 262 is outside")
    }

    /**
     * Spec test 7: a soft mask edge (coverage 128) FILL on empty -> alpha 128, colour premultiplied
     * (128, 0, 0, 128).
     *
     * DERIVATION. `a = 128/255` exactly, and on an empty layer `D' = S = (255a, 0, 0, 255a)` =
     * (128, 0, 0, 128) with no rounding at all — which is the whole point of a premultiplied
     * source: half a pixel of red at half coverage is exactly half a pixel of red.
     */
    @Test
    fun aSoftMaskEdgeFillsAsAHalfAlphaPixel() {
        val raw = ByteArray(4 * 4) { 128.toByte() }
        val mask = SelectionMask.fromMask(4, 4, raw, 0, 0)
        val tile = assertNotNull(
            MaskPaint.apply(emptyMap(), mask, 0xFFFF0000.toInt(), 1f, MaskPaintMode.FILL)[Tiles.key(0, 0)],
        )
        for (y in 0 until 4) {
            for (x in 0 until 4) {
                val at = (y * Tiles.SIZE + x) * 4
                val got = (0..3).map { tile[at + it].toInt() and 0xFF }
                assertEquals(listOf(128, 0, 0, 128), got, "($x,$y)")
            }
        }
    }

    // ── the two callers ───────────────────────────────────────────────────────────

    /**
     * THE TAP FILL'S REAL CALLER, wired end to end: a `FloodFill` region becomes a
     * [SelectionMask] through `fromMask` and is painted by [MaskPaint.apply]. The spec's reason
     * for one function and two callers is that this path exists, so it is run rather than
     * described.
     */
    @Test
    fun aFloodFillResultPaintsThroughTheSameFunction() {
        val w = 24
        val h = 24
        val rgba = ByteArray(w * h * 4)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val onLine = (x == 6 || x == 17) && y in 6..17 || (y == 6 || y == 17) && x in 6..17
                val v = if (onLine) 0 else 255
                val at = (y * w + x) * 4
                rgba[at] = v.toByte(); rgba[at + 1] = v.toByte()
                rgba[at + 2] = v.toByte(); rgba[at + 3] = 255.toByte()
            }
        }
        val region = FloodFill.fill(w, h, rgba, 12, 12, FillOptions(tolerance = 0.1f, grow = 0))
        assertTrue(region.any { it.toInt() != 0 }, "the flood found no region at all")
        val mask = SelectionMask.fromMask(w, h, region, 0, 0)
        assertFalse(mask.isEmpty)
        val tile = assertNotNull(
            MaskPaint.apply(emptyMap(), mask, 0xFF20C0F0.toInt(), 1f, MaskPaintMode.FILL)[Tiles.key(0, 0)],
        )
        var filled = 0
        for (y in 0 until h) {
            for (x in 0 until w) {
                if (region[y * w + x].toInt() == 0) continue
                filled++
                val at = (y * Tiles.SIZE + x) * 4
                assertEquals(0xF0.toInt(), tile[at + 2].toInt() and 0xFF, "($x,$y) blue")
                assertEquals(255, tile[at + 3].toInt() and 0xFF, "($x,$y) alpha")
            }
        }
        // The region is the inside of the outline at (6,6)..(17,17), so 9 x 9 = 81 px — the
        // outline itself is black and so is not within tolerance of white. A loose band, because
        // the exact count is FloodFill's business and not this file's.
        assertTrue(filled in 60..100, "filled $filled px; the box interior is 81")
    }

    /** THE FILL PEN'S REAL CALLER, wired the same way: outline -> polygon -> paint. */
    @Test
    fun aFillPenShapePaintsAsAShape() {
        val outline = listOf(Pt(40.0, 20.0), Pt(120.0, 30.0), Pt(80.0, 100.0))
        val mask = SelectionMask.polygon(outline)
        assertFalse(mask.isEmpty)
        val tile = assertNotNull(
            MaskPaint.apply(emptyMap(), mask, 0xFFFFC000.toInt(), 1f, MaskPaintMode.BEHIND)[Tiles.key(0, 0)],
        )
        var solid = 0
        var weighted = 0L
        for (y in 0 until 110) {
            for (x in 0 until 130) {
                val c = mask.coverage(x, y)
                if (c == 0) continue
                val at = (y * Tiles.SIZE + x) * 4
                // BEHIND onto an empty layer is `S + 0`, so the pixel is the source premultiplied
                // BY ITS OWN COVERAGE: alpha = 255*c/255 = c, and each colour = 255*(c/255).
                val wantAlpha = c
                assertEquals(wantAlpha, tile[at + 3].toInt() and 0xFF, "($x,$y) alpha is the coverage")
                assertEquals(
                    wantAlpha, tile[at].toInt() and 0xFF,
                    "($x,$y) red: 0xEE is 238, so 238*c/255 rounds to the coverage itself at c = 255 " +
                        "and to a proportional value below it",
                )
                assertTrue(
                    tile[at].toInt() and 0xFF <= tile[at + 3].toInt() and 0xFF,
                    "($x,$y) red is above alpha, which is not a premultiplied pixel",
                )
                weighted += c.toLong()
                if (c == 255) solid++
            }
        }
        // Shoelace: the polygon area is |sum(x_i*y_j - x_j*y_i)|/2 over the closed loop. The
        // weighted coverage sum must be within antialiasing of it — this is an AREA check, not a
        // per-pixel expected value, which is the point.
        //
        // THE TOLERANCE, derived rather than fitted. The outline's edges are DIAGONAL — (40,20) to
        // (120,30) to (80,100) — so this polygon is not a rect and its boundary really is fractional.
        // A 4 x 4 supersampler gives each pixel `round(subpixels * 255 / 16)`, and `round` is off by
        // at most half a unit, so the SUM is off from the exact area by at most half a unit per
        // BOUNDARY pixel; interior pixels are exactly 255 and exterior exactly 0 and contribute
        // nothing. A monotone edge of span dx by dy crosses at most dx + dy pixels, and this
        // triangle's three edges give 80+10, 40+70 and 40+80, so at most 320 boundary pixels and
        // therefore at most 160 units of error. The observed value is 10 — two orders of magnitude
        // inside the bound, and the bound still catches a stride or tile-origin error, which lands
        // in the tens of thousands. An exact `assertEquals` here was simply wrong: the comment above
        // it had said "within antialiasing" all along, and the assertion had not believed it.
        val area = abs(
            outline.indices.sumOf { i ->
                val a = outline[i]
                val b = outline[(i + 1) % outline.size]
                a.x * b.y - b.x * a.y
            },
        ) / 2.0
        val error = abs(weighted - (area * 255).toLong())
        assertTrue(
            error <= 160L,
            "the shape's coverage sum is $weighted against an area of $area ($((area * 255).toLong()}), " +
                "a difference of $error where at most 160 is antialiasing",
        )
        // The SOLID count, against the same boundary budget and for the same reason. A 4 x 4
        // supersampler marks a pixel 255 only when all 16 subsamples fall inside, so every boundary
        // pixel of a DIAGONAL edge is partial, and "almost every interior pixel" is not the same
        // thing as "2 % may be partial" on a shape with 250 px of slanted perimeter. The bound is
        // the same 320: at most one non-solid interior pixel per boundary pixel. Observed 110.
        // A stride or tile-origin error puts this in the thousands, so the bound still has teeth.
        assertTrue(
            abs(solid - area) <= 320.0,
            "only $solid px are SOLID, against an area of $area — at most 320 may be partial " +
                "boundary pixels of a 250 px slanted perimeter",
        )
    }

    // ── the edges ─────────────────────────────────────────────────────────────────

    /** A short tile is a caller bug, and it is caught before any index is made of it. */
    @Test
    fun aTileOfTheWrongSizeIsRefusedWithWords() {
        val mask = SelectionMask.rect(RectPx(0, 0, 4, 4))
        val e = assertFailsWith<IllegalArgumentException> {
            MaskPaint.apply(
                mapOf(Tiles.key(0, 0) to ByteArray(10)), mask, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL,
            )
        }
        assertTrue(e.message!!.contains("10 bytes"), "the message names the size: ${e.message}")
    }

    /** An empty mask paints nothing, and says so by returning nothing. */
    @Test
    fun anEmptyMaskPaintsNothing() {
        assertTrue(
            MaskPaint.apply(emptyMap(), SelectionMask.EMPTY, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL)
                .isEmpty(),
        )
        // A polygon of two points is a lasso that was never closed, and rasterises to nothing.
        val stub = SelectionMask.polygon(listOf(Pt(0.0, 0.0), Pt(9.0, 9.0)))
        assertTrue(stub.isEmpty)
        assertTrue(
            MaskPaint.apply(emptyMap(), stub, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL).isEmpty(),
        )
    }

    /** Only tiles the mask reaches are visited, so a tile it does not reach is not even read. */
    @Test
    fun onlyTilesTheMaskReachesAreVisited() {
        val mask = SelectionMask.rect(RectPx(300, 20, 4, 4))
        val far = solidTile(0, 0, 0, 255)
        val layer = mapOf(Tiles.key(0, 0) to far, Tiles.key(1, 0) to solidTile(256, 0, 0, 255))
        val changed = MaskPaint.apply(layer, mask, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL)
        assertEquals(listOf(Tiles.key(1, 0)), changed.keys.toList())
        assertContentEquals(far, layer.getValue(Tiles.key(0, 0)), "the far tile was rewritten")
    }

    /**
     * NaN AND OUT-OF-RANGE OPACITY, which is where a slider and a NaN both end up.
     *
     * A NaN is 1, not 0 and not a silent no-op. `Double.coerceIn` returns NaN for NaN (every
     * comparison with NaN is false), and a NaN reaching `a` would make every downstream comparison
     * false and the fill would return an EMPTY change set — a fill that looks exactly like a tap
     * that missed. Out of range is CLAMPED, because it comes off a slider.
     */
    @Test
    fun opacityIsClampedAndNaNBecomesOne() {
        val mask = SelectionMask.rect(RectPx(0, 0, 4, 4))
        val empty = mapOf(Tiles.key(0, 0) to solidTile(0, 0, 0, 0))
        val one = MaskPaint.apply(empty, mask, 0xFFFFFFFF.toInt(), 1f, MaskPaintMode.FILL)
        assertContentEquals(
            one[Tiles.key(0, 0)],
            MaskPaint.apply(empty, mask, 0xFFFFFFFF.toInt(), Float.NaN, MaskPaintMode.FILL)[Tiles.key(0, 0)],
            "NaN must behave as 1",
        )
        assertContentEquals(
            one[Tiles.key(0, 0)],
            MaskPaint.apply(empty, mask, 0xFFFFFFFF.toInt(), 4f, MaskPaintMode.FILL)[Tiles.key(0, 0)],
            "4 is clamped to 1",
        )
        assertTrue(
            MaskPaint.apply(empty, mask, 0xFFFFFFFF.toInt(), -2f, MaskPaintMode.FILL).isEmpty(),
            "-2 is clamped to 0, which is a no-op in every mode",
        )
    }

    /** The one-pixel door refuses what it cannot do, rather than writing over its own input. */
    @Test
    fun theOnePixelDoorRefusesWhatItCannotDo() {
        assertFailsWith<IllegalArgumentException> {
            pixel(MaskPaintMode.FILL, 0, 1f, 255, IntArray(3), IntArray(4))
        }
        assertFailsWith<IllegalArgumentException> {
            pixel(MaskPaintMode.FILL, 0, 1f, 255, IntArray(4), IntArray(2))
        }
        val alias = IntArray(4)
        assertFailsWith<IllegalArgumentException> {
            pixel(MaskPaintMode.FILL, 0, 1f, 255, alias, alias)
        }
    }

    /**
     * The rounding, named directly.
     *
     * `floor(v + 0.5)` — the form the rest of the engine uses (`Resample.toByte255`,
     * `SelectionMask.subtract`) — returns 1 for `0.49999999999999994`, because that plus 0.5 is
     * exactly 1.0 in IEEE 754. The truncating form [MaskPaint.round255] uses is exact for every
     * double, and this is the case that proves it.
     */
    @Test
    fun theRoundingIsExactAtTheHalfAndNotOneUlpPastIt() {
        assertEquals(1, MaskPaint.round255(0.5), "0.5 rounds UP (half up, as documented)")
        assertEquals(0, MaskPaint.round255(0.49999999999999994), "one ULP below 0.5 rounds DOWN")
        assertEquals(0, MaskPaint.round255(0.4999999999999999), "and so do two ULPs below")
        assertEquals(255, MaskPaint.round255(254.5))
        assertEquals(254, MaskPaint.round255(254.49999999999997), "one ULP below 254.5 rounds DOWN")
        assertEquals(0, MaskPaint.round255(0.0))
        assertEquals(0, MaskPaint.round255(-3.0), "clamped, not wrapped: a negative becomes 0")
        assertEquals(255, MaskPaint.round255(1e9), "clamped, not wrapped: a huge value becomes 255")
        for (k in 0..255) {
            val base = k.toDouble()
            assertEquals(k, MaskPaint.round255(base), "$base")
            // `nextDown`, NOT `base + 0.49999999999999994`. That literal is a trap, and it made this
            // test assert two contradictory things at once: for every integer `base` in this range,
            // `base + 0.49999999999999994` rounds back UP to exactly `base + 0.5` in the addition
            // (the true sum sits within half an ULP of it), so the expression is `base + 0.5` and
            // the correct answer is `k + 1` — which is what the very next line asserts. The literal
            // is only a value strictly below `0.5` when `base` is 0, which is line 2 above.
            // `nextDown(base + 0.5)` says "just under the half" and MEANS it, for every `k`.
            val justUnder = (base + 0.5).nextDown()
            assertTrue(justUnder < base + 0.5, "nextDown must really be under the half at $base")
            assertEquals(k, MaskPaint.round255(justUnder), "$base + just under .5")
            // And the same value through the form this function exists to avoid. It is wrong at
            // k = 0 and RIGHT everywhere else, which is the honest shape of the problem and worth
            // pinning exactly rather than rounding off in a comment: at k = 0 the sum is
            // 0.9999999999999999444, within half an ULP of 1.0, so the addition rounds it up to
            // exactly 1.0 and `floor` returns 1 for a value that must round DOWN to 0. From k = 1
            // upward the sum is representable and `floor` happens to land right. A function that is
            // wrong once in 256 is wrong, because the once is a pixel.
            if (k == 0) {
                assertEquals(1, floor(justUnder + 0.5).toInt(), "floor(v+0.5) is the wrong one — here")
            } else {
                assertEquals(k, floor(justUnder + 0.5).toInt(), "floor(v+0.5) happens to agree at $k")
            }
            // The top of the range is where the CLAMP is, not the rounding: 255.5 and anything just
            // over it round to 256, which is not a byte, and the documented answer is 255. So k = 255
            // expects k and not k + 1 — asserted explicitly rather than left to fall out of a
            // `coerceAtMost` nobody thought about when the sweep was written.
            val top = k == 255
            assertEquals(if (top) k else k + 1, MaskPaint.round255(base + 0.5), "$base + .5")
            assertEquals(
                if (top) k else k + 1, MaskPaint.round255((base + 0.5).nextUp()),
                "$base + just over .5" + if (top) " (clamped, not wrapped)" else "",
            )
        }
    }

    /** Every pixel that comes out is premultiplied, whatever it was painted onto. */
    @Test
    fun everyPixelThatComesOutIsPremultiplied() {
        val out = IntArray(4)
        // The last two are NOT premultiplied (colour > alpha), which is what the clamp is for.
        val dests = arrayOf(
            intArrayOf(0, 0, 0, 0), intArrayOf(255, 0, 0, 255), intArrayOf(200, 10, 90, 200),
            intArrayOf(0, 0, 0, 128), intArrayOf(255, 255, 255, 255), intArrayOf(255, 0, 0, 3),
        )
        for (mode in MaskPaintMode.entries) {
            for (argb in listOf(0xFFFF0000.toInt(), 0xFF204080.toInt(), 0xFF000000.toInt(), 0xFFFFFFFF.toInt())) {
                for (opacity in listOf(1f, 0.5f, 0.1f)) {
                    for (dest in dests) {
                        for (c in 0..255) {
                            pixel(mode, argb, opacity, c, dest, out)
                            for (ch in 0..2) {
                                assertTrue(
                                    out[ch] <= out[3],
                                    "mode $mode coverage $c opacity $opacity dest ${dest.joinToString(",")}: " +
                                        "channel $ch = ${out[ch]} exceeds alpha ${out[3]}",
                                )
                            }
                        }
                    }
                }
            }
        }
    }

    // ── helpers ───────────────────────────────────────────────────────────────────

    /** The one-pixel door, handing back [out] so a test can read it without allocating twice. */
    private fun pixel(
        mode: MaskPaintMode,
        argb: Int,
        opacity: Float,
        coverage: Int,
        dest: IntArray,
        out: IntArray,
    ): IntArray {
        MaskPaint.pixel(mode, argb, opacity, coverage, dest, out)
        return out
    }

    /**
     * The masks the bridge test walks, chosen so the walk has to be right about: a shape whose
     * coverage is soft in the middle of an edge, a shape across the x = 256 seam, a shape across
     * the y = 256 seam AND at negative coordinates (where `tileOfPx` FLOORS, and a truncating
     * division files pixel -1 in tile 0 with a negative local index), and a shape with a HOLE,
     * so the antialiased rim of an inner edge is in the comparison too.
     */
    private fun shapes(): List<SelectionMask> = listOf(
        SelectionMask.polygon(
            listOf(
                Pt(12.5, 9.25), Pt(180.75, 40.5), Pt(96.0, 150.125),
                Pt(30.0, 120.0), Pt(160.0, 100.5),
            ),
        ),
        SelectionMask.polygon(
            listOf(Pt(240.0, 20.0), Pt(272.0, 20.0), Pt(272.0, 90.0), Pt(240.0, 90.0)),
        ),
        SelectionMask.polygon(
            listOf(Pt(-40.0, 250.0), Pt(30.0, 250.0), Pt(30.0, 280.0), Pt(-40.0, 280.0)),
        ),
        SelectionMask.polygon(
            listOf(
                Pt(300.0, 300.0), Pt(420.0, 300.0), Pt(420.0, 420.0), Pt(300.0, 420.0),
                Pt(340.0, 340.0), Pt(340.0, 380.0), Pt(380.0, 380.0), Pt(380.0, 340.0),
            ),
        ),
    )

    /** A full tile of one premultiplied colour. */
    private fun solidTile(r: Int, g: Int, b: Int, a: Int): ByteArray {
        val t = ByteArray(Tiles.SIZE * Tiles.SIZE * 4)
        for (i in t.indices step 4) {
            t[i] = r.toByte(); t[i + 1] = g.toByte(); t[i + 2] = b.toByte(); t[i + 3] = a.toByte()
        }
        return t
    }

    /**
     * A premultiplied destination that VARIES with position, so an indexing bug in the tile walk
     * cannot pass by reading the same constant backdrop every time. The colours are written under
     * the alpha, so this is a legal premultiplied pixel at every point — the illegal ones are in
     * [everyPixelThatComesOutIsPremultiplied].
     *
     * THROUGH THE PIXEL'S CENTRE, and that is not a style choice. `x` and `y` here are the LOWER-LEFT
     * DOCUMENT INDEX of a pixel, and the mirror of pixel index `i` under `(x, y) -> (-x, -y)` is
     * `-i - 1`, not `-i`: pixel `i` covers `[i, i+1)` and its mirror covers `[-i-1, -i)`. So `abs(i)`
     * is NOT the mirror of `abs(-i-1)` — for `i = 20` the two are 20 and 21 — and a ramp built on
     * `abs(i)` is not symmetric under the reflection the test is about. `abs(2*i + 1)` is: it is
     * `|centre|` in doubled units, and `|2*(-i-1) + 1| = |2*i + 1|`.
     *
     * This was a real red test, not a hypothetical: the whole-tile alpha totals differed by 19 808
     * with the index-based ramp, and the difference was entirely in the part of the tile the fill
     * never touched, because tile `(0, 0)` spans indices `0..255` (so `px` runs 0..255) while tile
     * `(-1, -1)` spans `-256..-1` (so `px` runs 1..256). The paint was symmetric the whole time.
     */
    private fun rampPixel(x: Int, y: Int): IntArray {
        val px = abs(2 * x + 1)
        val py = abs(2 * y + 1)
        val a = (px * 2 + py) % 200 + 55
        return intArrayOf(
            ((px + py) % 200).coerceAtMost(a),
            ((px + py) / 2 % 200).coerceAtMost(a),
            ((px * 3 + py) % 200).coerceAtMost(a),
            a,
        )
    }

    /** A layer of [rampPixel] over every tile the mask reaches. */
    private fun rampLayer(mask: SelectionMask): Map<Long, ByteArray> {
        val out = LinkedHashMap<Long, ByteArray>()
        for (key in mask.tileKeys) {
            val t = ByteArray(Tiles.SIZE * Tiles.SIZE * 4)
            val ox = Tiles.tx(key) * Tiles.SIZE
            val oy = Tiles.ty(key) * Tiles.SIZE
            for (row in 0 until Tiles.SIZE) {
                for (col in 0 until Tiles.SIZE) {
                    val p = rampPixel(ox + col, oy + row)
                    val at = (row * Tiles.SIZE + col) * 4
                    t[at] = p[0].toByte(); t[at + 1] = p[1].toByte()
                    t[at + 2] = p[2].toByte(); t[at + 3] = p[3].toByte()
                }
            }
            out[key] = t
        }
        return out
    }

    /**
     * A change set turned back into a layer, the way `GlPaintEngine.replaceTiles` applies one: a
     * `null` DELETED the tile, so a change set read back as a layer drops those keys rather than
     * inventing an all-zero tile for them. Feeding a change set straight back into [MaskPaint.apply]
     * is a type error rather than a silent wrong answer, which is the right way round.
     */
    private fun Map<Long, ByteArray?>.asLayer(): Map<Long, ByteArray> {
        val out = LinkedHashMap<Long, ByteArray>()
        for ((k, v) in this) if (v != null) out[k] = v
        return out
    }

    /** Total alpha over every tile of a change set — a whole picture reduced to one number. */
    private fun totalAlpha(changed: Map<Long, ByteArray?>): Long {
        var sum = 0L
        for (bytes in changed.values) {
            val t = assertNotNull(bytes, "a fill never empties a tile; a null here is a bug")
            for (i in t.indices step 4) sum += (t[i + 3].toInt() and 0xFF).toLong()
        }
        return sum
    }

    /** The mask's own coverage total over a box, computed through `coverage(x, y)`. */
    private fun coverageSum(mask: SelectionMask, r: RectPx): Long {
        var sum = 0L
        for (y in r.y until r.y + r.h) {
            for (x in r.x until r.x + r.w) sum += mask.coverage(x, y)
        }
        return sum
    }
}
